const data = {
  products: [
    {
      _id: "1",
      name: "Slim Shirt",
      category: "Shirts",
      image: "/images/d1.jpg",
      price: 60,
      brand: "Nike",
      rating: 4.2,
      numReviews: 5,
      countInStock: 6,
    },
    {
      _id: "2",
      name: "Fit Shirt",
      category: "Shirts",
      image: "/images/d2.jpg",
      price: 70,
      brand: "Nike",
      rating: 4.1,
      numReviews: 5,
      countInStock: 7,
    },
    {
      _id: "3",
      name: "Best Pants",
      category: "Pants",
      image: "/images/d3.jpg",
      price: 80,
      brand: "Nike",
      rating: 4.5,
      numReviews: 5,
      countInStock: 8,
    },
    {
      _id: "4",
      name: "Nice Pants",
      category: "Pants",
      image: "/images/p1.jpg",
      price: 90,
      brand: "Nike",
      rating: 4.8,
      numReviews: 5,
      countInStock: 9,
    },
    {
      _id: "5",
      name: "Not Bat Pants",
      category: "Pants",
      image: "/images/p2.jpg",
      price: 60,
      brand: "Nike",
      rating: 3.7,
      numReviews: 5,
      countInStock: 10,
    },
    {
      _id: "6",
      name: "Bad Pants",
      category: "Pants",
      image: "/images/p3.jpg",
      price: 65,
      brand: "Nike",
      rating: 3.9,
      numReviews: 5,
      countInStock: 11,
    },
  ],
};
export default data;
