const data = {
  products: [
    {
      _id: 1,
      name: "Slim Shirt",
      category: "Shirts",
      image: "/images/d1.jpg",
      price: 60,
      brand: "Nike",
      rating: 4.2,
      numReviews: 10,
    },
    {
      _id: 2,
      name: "Fit Shirt",
      category: "Shirts",
      image: "/images/d1.jpg",
      price: 70,
      brand: "Nike",
      rating: 4.1,
      numReviews: 10,
    },
    {
      _id: 3,
      name: "Best Pants",
      category: "Pants",
      image: "/images/d1.jpg",
      price: 80,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
    },
    {
      _id: 4,
      name: "Nice Pants",
      category: "Pants",
      image: "/images/d1.jpg",
      price: 90,
      brand: "Nike",
      rating: 4.8,
      numReviews: 10,
    },
    {
      _id: 5,
      name: "Not Bat Pants",
      category: "Pants",
      image: "/images/d1.jpg",
      price: 60,
      brand: "Nike",
      rating: 3.7,
      numReviews: 10,
    },
    {
      _id: 5,
      name: "Not Bad Shirt",
      category: "Shirts",
      image: "/images/d1.jpg",
      price: 65,
      brand: "Nike",
      rating: 3.9,
      numReviews: 10,
    },
  ],
};
export default data;
